<?php

namespace Idk\LegoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IdkFinderFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachableFolderRepository extends EntityRepository
{

	public function findRacine(){
        $qb = $this->createQueryBuilder('f');
        $qb->andWhere('f.folder is NULL');
        return $qb->getQuery()->getResult();
    }

    public function findRacineByClassAndItemId($class,$itemId,$zoneCode = null){
        $qb = $this->createQueryBuilder('f');
        $qb->andWhere('f.folder is NULL');
        $qb->andWhere('f.itemId = :itemId')->setParameter('itemId',$itemId);
        $qb->andWhere('f.class = :class')->setParameter('class',$class);
        if($zoneCode)  $qb->andWhere('f.zoneCode = :zone')->setParameter('zone',$zoneCode);
        return $qb->getQuery()->getResult();
    }

}
